services:
  - type: web
    name: aigc-creative
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python run.py
    envVars:
      - key: QINIU_ACCESS_KEY
        sync: false
      - key: QINIU_SECRET_KEY
        sync: false
      - key: QINIU_BUCKET_NAME
        sync: false
      - key: QINIU_DOMAIN
        sync: false
      - key: DASHSCOPE_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PORT
        sync: false
        value: 10000
